- 👋 Hi, I’m @Brookscomp
- 👀 I’m interested in ...air drops . Supporting upcoming crypto currency's donations an expanding my brand on meta.V
- 🌱 I’m currently learning ... new controls. An emphasizizing what would be needed to make the moments more enjoyable for others.
- 💞️ I’m looking to collaborate on ...with designers ,lancers an any one who is willing to be apart of the journey.I would love to play a part in your path for success (O.G.E) .stay focused 
- 📫 How to reach me ...
I'm reachable at brookswill999@gmail.com.
<!---
Brookscomp/Brookscomp is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
